# Generated by Django 6.0 on 2025-12-17 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_product_reserved_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='total_stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
