# Generated by Django 6.0 on 2025-12-18 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='id',
            field=models.UUIDField(default='3197da97-d22a-4bd4-85d3-7e7c1a40c545', editable=False, primary_key=True, serialize=False),
        ),
    ]
