# Generated by Django 6.0 on 2025-12-18 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_reservation_order_alter_reservation_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='confirm',
            field=models.BooleanField(default=False),
        ),
    ]
